/******************************************************************************

Welcome to GDB Online.
GDB online is an online compiler and debugger tool for C, C++, Python, Java, PHP, Ruby, Perl,
C#, VB, Swift, Pascal, Fortran, Haskell, Objective-C, Assembly, HTML, CSS, JS, SQLite, Prolog.
Code, Compile, Run and Debug online from anywhere in world.

*******************************************************************************/
/*
Diwali is here. While everyone here is busy texting "Happy Diwali" wishes to everybody else, NinjaCoder has some other plans and wants to earn some money this season.
Now, the Apex court has allowed the sale of only green crackers this Diwali. Out of all green crackers, "Chakri" is most popular. Because of the irregular supply of "Chakri", the price of "Chakri" is oscillating daily. NinjaCoder saw a business opportunity in this. He/She got a price list for coming N days from an insider in the market union. Prices in the list are for 1 unit of a large packet of "Chakri". Each large packet contains 100 units of Chakri.
Now, due to financial limitations, NinjaCoder can transact only 1 large packet (100 units of "Chakri") in the market. You have to tell maximum profit possible, given that he/she can transact atmost one time.
Note: 1. Transaction refers to the act of buying and selling.
      2. "Chakri" cannot be sold individually. NinjaCoder has to buy/sell the entire packet. 
      
First-line contains N - (Integer)
Second-line contains N spaced integers.

1 <= N <= 10000
50 <= A(i) <= 100

Print the maximum profit that can be generated by NinjaCoder.

SAMPLE INPUT:
7
62 63 70 66 64 68 61
SAMPLE OUTPUT:
8


*/

import java.util.Scanner;

public class Main {

	
	public static void main(String[] args) {
		// Write your code here
        Scanner sc=new Scanner(System.in);
        int n=sc.nextInt();
        int arr[]=new int[n];
        for(int i=0;i<n;i++){
           
            arr[i]=sc.nextInt();
            
        }
        
        int cp=0,sp=0,mp=0;
        for(int i=0;i<n-1;i++){
            cp=arr[i];
            int pr=0;
            for(int j=i+1;j<n;j++){
                sp=arr[j];
                pr=sp-cp;
                if(pr>mp)
                    mp=pr;
            }
        }
        System.out.println(mp);

	}

}